---
- name: Gather package facts on target hosts
  ansible.builtin.package_facts:
    manager: auto

- name: Install required packages if not installed
  become: true
  become_user: root
  when: qwgd not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ qwgd }}"
    state: present
  loop: "{{ containers_package_manifest }}"
  loop_control:
    loop_var: qwgd
    label: "Installing missing package {{ qwgd }}"

- name: Gather facts about container to be removed
  when: containers_runtime_image_state == 'absent'
  containers.podman.podman_container_info:
    name: "{{ containers_runtime_name }}"
  register: containers_registered_facts

- name: Assert a container exists before trying to remove
  when: containers_registered_facts is not skipped
  ansible.builtin.assert:
    that:
      - containers_registered_facts.containers | length > 0
    fail_msg: >-
      Cannot remove {{ containers_runtime_name }} as it does
      not exist on {{ inventory_hostname }}
