---
- name: Deploy a container on the target host
  when: containers_runtime_image_state == 'present'
  containers.podman.podman_container:
    image: >-
      {{ containers_registry
       ~ '/'
       ~ containers_registry_image_name
       ~ ':'
       ~ containers_registry_image_tag
      }}
    name: "{{ containers_runtime_name }}"
    network: host
    state: started
