---
- name: Login to container registry
  when:
    - containers_registry is defined
    - containers_registry_user is defined
    - containers_registry_token is defined
  containers.podman.podman_login:
    registry: "{{ containers_registry }}"
    username: "{{ containers_registry_user }}"
    password: "{{ containers_registry_token }}"
