argument_specs:
  main:
    options:
      containers_package_manifest:
        type: list
        elements: str
        required: false
        description: Packages to install on target host
      containers_runtime_name:
        type: str
        required: true
        description: String to use when naming the container at runtime
      containers_registry:
        type: str
        default: ""
        description: Registry url with namespace
      containers_registry_user:
        type: str
        default: ""
        no_log: true
        description: Username to use to login to a registry
      containers_registry_token:
        type: str
        default: ""
        no_log: true
        description: Token to use to login to a registry
      containers_runtime_image:
        type: str
        required: true
        description: Name of the container image to pull and deploy
      containers_runtime_image_tag:
        type: str
        default: latest
        description: Image tag to pull from registry
      containers_runtime_image_state:
        type: str
        required: true
        description: Expected state of container on target host
        choices:
          - present
          - absent
